In [1]:
import pandas as pd
import numpy as np
import sklearn as sk

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split

In [3]:
TD3 = pd.read_csv('Datasets/TrainData3.txt', sep="\t", header=None)
TL3 = pd.read_csv('Datasets/TrainLabel3.txt', sep="\t", header=None)
TestD3 = pd.read_csv('Datasets/TestData3.txt', sep="\t", header=None)

In [4]:
TD3.fillna(TD3.median(), inplace=True)
TestD3.fillna(TestD3.median(), inplace=True)
TD3cat = pd.concat([TD3, TL3], axis=1)
print(TD3.shape)
print(TL3.shape)
print(TestD3.shape)

(6300, 13)
(6300, 1)
(2693, 13)


In [5]:
x3 = TD3cat.iloc[:,0:]
y3 = TD3cat.iloc[:,13]

x_real3 = TD3.iloc[:,0:]
y_real3 = TL3.iloc[:,0]

In [6]:
X_train3, X_test3, y_train3, y_test3 = train_test_split(x3, y3, test_size = 0.2, random_state = 0)

In [25]:
LR = LogisticRegression(random_state=0, solver='newton-cg', max_iter=300, multi_class='multinomial').fit(X_train3, y_train3)
LR.predict(X_test3)
round(LR.score(X_test3,y_test3), 4)

1.0

In [20]:
LR = LogisticRegression(random_state=0, solver='newton-cg', max_iter=500, multi_class='multinomial').fit(x_real3, y_real3)
result = LR.predict(TestD3)
print(*result, sep = ", ") 

8, 8, 1, 1, 4, 1, 1, 1, 8, 9, 8, 9, 1, 9, 6, 6, 8, 8, 8, 8, 8, 8, 8, 2, 7, 8, 1, 1, 1, 1, 1, 1, 9, 8, 1, 1, 1, 1, 6, 6, 6, 8, 8, 8, 6, 1, 1, 8, 1, 6, 1, 8, 1, 4, 6, 4, 9, 1, 6, 1, 8, 8, 9, 6, 1, 1, 1, 9, 8, 8, 8, 8, 1, 9, 8, 8, 8, 6, 8, 1, 8, 1, 9, 1, 9, 8, 1, 1, 6, 6, 1, 8, 8, 6, 1, 6, 8, 1, 1, 1, 8, 8, 8, 4, 6, 8, 1, 8, 1, 8, 9, 6, 1, 6, 1, 1, 1, 1, 6, 9, 1, 1, 6, 1, 1, 1, 1, 1, 1, 6, 1, 8, 1, 8, 8, 6, 4, 1, 6, 1, 8, 8, 1, 1, 1, 6, 4, 9, 1, 6, 8, 8, 1, 6, 1, 8, 1, 9, 1, 4, 8, 6, 8, 1, 2, 8, 1, 6, 1, 1, 8, 6, 8, 1, 8, 1, 7, 6, 8, 8, 6, 1, 6, 8, 1, 1, 8, 6, 8, 6, 8, 6, 1, 8, 1, 1, 1, 1, 6, 1, 1, 8, 6, 1, 8, 1, 1, 8, 8, 8, 4, 1, 6, 8, 3, 1, 8, 4, 8, 5, 6, 6, 8, 8, 8, 6, 1, 8, 6, 8, 8, 2, 1, 9, 2, 7, 8, 6, 9, 9, 9, 8, 6, 6, 8, 1, 7, 1, 8, 1, 6, 7, 1, 1, 6, 8, 8, 7, 6, 8, 8, 6, 6, 8, 1, 2, 8, 2, 1, 8, 1, 6, 9, 2, 9, 8, 1, 8, 6, 6, 1, 8, 8, 7, 6, 6, 8, 8, 8, 7, 1, 8, 8, 8, 1, 1, 1, 8, 1, 6, 6, 4, 6, 4, 4, 8, 6, 8, 7, 6, 8, 8, 1, 1, 6, 2, 1, 7, 3, 8, 6, 2, 6, 6, 8, 4, 1, 1, 5, 4, 8, 6, 8, 6

In [21]:
SVM = svm.SVC(kernel='linear', decision_function_shape="ovo").fit(X_train3, y_train3)
SVM.predict(X_test3)
round(SVM.score(X_test3, y_test3), 4)

1.0

In [22]:
SVM = svm.SVC(kernel='linear', decision_function_shape="ovo").fit(x_real3, y_real3)
result = SVM.predict(TestD3)
print(result)

[8 8 1 ... 1 6 4]


In [11]:
RF = RandomForestClassifier(n_estimators=1000, max_depth=10, random_state=0).fit(X_train3, y_train3)
RF.predict(X_test3)
round(RF.score(X_test3, y_test3), 4)

0.9452

In [12]:
RF = RandomForestClassifier(n_estimators=1000, max_depth=10, random_state=0).fit(x_real3, y_real3)
result = RF.predict(TestD3)
print(result)

[8 8 1 ... 1 6 5]


In [24]:
NN = MLPClassifier(solver='adam', alpha=1e-5, hidden_layer_sizes=(150, 10), random_state=1).fit(X_train3, y_train3)
NN.predict(X_test3)
round(NN.score(X_test3, y_test3), 4)

C:\Users\Rhine\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


0.9175

In [14]:
NN = MLPClassifier(solver='adam', alpha=1e-5, hidden_layer_sizes=(150, 10), random_state=1).fit(x_real3, y_real3)
result = NN.predict(TestD3)
print(result)

[8 8 1 ... 1 6 6]
